### ISSUE TITLE
mvn test failed

### ISSUE THREAD

**Issue by calaba** [Netflix/Surus#1]
C:\OpenSource\Netflix\Surus\Surus>mvn test
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building scoring 0.1.2
[INFO] ------------------------------------------------------------------------
Downloading: http://artifacts.netflix.com/ext-releases-local/amazon/hadoop-core-emr/1.0.3/hadoop-core-emr-1.0.3.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.891s
[INFO] Finished at: Wed Jan 21 18:30:02 PST 2015
[INFO] Final Memory: 9M/241M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project scoring: Could not resolve dependencies for project netflix:scoring:jar:0.1.2: Failed to collect dependencies at amazo
n:hadoop-core-emr:jar:1.0.3: Failed to read artifact descriptor for amazon:hadoop-core-emr:jar:1.0.3: Could not transfer artifact amazon:hadoop-core-emr:pom:1.0
.3 from/to netflix-ext-releasess (http://artifacts.netflix.com/ext-releases-local): artifacts.netflix.com: Unknown host artifacts.netflix.com -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
C:\OpenSource\Netflix\Surus\Surus>

**Comment by rajeshkp** [comment]
I see the same error as well, I don't think the artifacts are externally resolvable.

[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building scoring 0.1.2
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for org.jpmml:pmml-evaluator:jar:1.0.19 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[WARNING] The POM for junit:junit-dep:jar:4.8.2 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[WARNING] The POM for amazon:hadoop-core-emr:jar:1.0.3 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[WARNING] The POM for org.apache.pig:pig:jar:0.14.0 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
Downloading: http://artifacts.netflix.com/ext-releases-local/org/jpmml/pmml-evaluator/1.0.19/pmml-evaluator-1.0.19.jar
Downloading: http://artifacts.netflix.com/ext-releases-local/org/apache/pig/pig/0.14.0/pig-0.14.0.jar
Downloading: http://artifacts.netflix.com/ext-releases-local/amazon/hadoop-core-emr/1.0.3/hadoop-core-emr-1.0.3.jar
[WARNING] Checksum validation failed, expected <!DOCTYPE but is a858799a2514f9a68547e7d917cf7f22d8f5d1ea for http://artifacts.netflix.com/ext-releases-local/amazon/hadoop-core-emr/1.0.3/hadoop-core-emr-1.0.3.jar
[WARNING] Checksum validation failed, expected <!DOCTYPE but is d6ef8c50fabcf0fe236fab40fde0d0dc8c74b2ec for http://artifacts.netflix.com/ext-releases-local/org/apache/pig/pig/0.14.0/pig-0.14.0.jar
[WARNING] Checksum validation failed, expected <!DOCTYPE but is b1dcd6cfbdd13512841ec1da18451ad12d5f584c for http://artifacts.netflix.com/ext-releases-local/org/jpmml/pmml-evaluator/1.0.19/pmml-evaluator-1.0.19.jar
[WARNING] Checksum validation failed, expected <!DOCTYPE but is a858799a2514f9a68547e7d917cf7f22d8f5d1ea for http://artifacts.netflix.com/ext-releases-local/amazon/hadoop-core-emr/1.0.3/hadoop-core-emr-1.0.3.jar
Downloaded: http://artifacts.netflix.com/ext-releases-local/amazon/hadoop-core-emr/1.0.3/hadoop-core-emr-1.0.3.jar (2 KB at 0.1 KB/sec)
[WARNING] Checksum validation failed, expected <!DOCTYPE but is d6ef8c50fabcf0fe236fab40fde0d0dc8c74b2ec for http://artifacts.netflix.com/ext-releases-local/org/apache/pig/pig/0.14.0/pig-0.14.0.jar
Downloaded: http://artifacts.netflix.com/ext-releases-local/org/apache/pig/pig/0.14.0/pig-0.14.0.jar (2 KB at 0.1 KB/sec)
[WARNING] Checksum validation failed, expected <!DOCTYPE but is b1dcd6cfbdd13512841ec1da18451ad12d5f584c for http://artifacts.netflix.com/ext-releases-local/org/jpmml/pmml-evaluator/1.0.19/pmml-evaluator-1.0.19.jar
Downloaded: http://artifacts.netflix.com/ext-releases-local/org/jpmml/pmml-evaluator/1.0.19/pmml-evaluator-1.0.19.jar (2 KB at 0.1 KB/sec)
[INFO]

**Comment by ccolburn** [comment]
@calaba and @rajeshkp : Thanks for pointing this out!  Obviously I had the dependencies setup for our internal environment.  I also took the opportunity to rename the package.  Let me know if you still have problems.
