### ISSUE TITLE
Cannot install R package

### ISSUE THREAD

**Issue by asstergiBSQ** [Netflix/Surus#5]
Hi,

The algorithm you've implemented seems great and I'm eager to try it on a project. However, I cannot install the R package: Here is the output:

> install_github(repo = "Surus", username = "Netflix", subdir = "resources/R/RAD")
Downloading github repo Netflix/Surus@master
Installing RAD
"C:/PROGRA~1/RRO/R-31~1.2/bin/x64/R" --vanilla CMD INSTALL  \
  "C:\Users\Stergios.-\AppData\Local\Temp\RtmpIv9Qjq\devtools1eec79a21cb8\Netflix-Surus-a1c24b9\resources\R\RAD"  \
  --library="C:/Users/Stergios.-/My Documents/R/win-library/3.1" --install-tests 

* installing *source* package 'RAD' ...
** libs
Warning: running command 'make -f "C:/PROGRA~1/RRO/R-31~1.2/etc/x64/Makeconf" -f "C:/PROGRA~1/RRO/R-31~1.2/share/make/winshlib.mk" SHLIB_LDFLAGS='$(SHLIB_CXXLDFLAGS)' SHLIB_LD='$(SHLIB_CXXLD)' SHLIB="RAD.dll" WIN=64 TCLBIN=64 OBJECTS="RcppExports.o anomaly_detection.o"' had status 127
ERROR: compilation failed for package 'RAD'
* removing 'C:/Users/Stergios.-/My Documents/R/win-library/3.1/RAD'
Error: Command failed (1)
In addition: Warning message:
Username parameter is deprecated. Please use Netflix/Surus

What could I try?

**Comment by mmolaro** [comment]
1) make sure RTools is installed and works, on PATH correctly
Try installing from my fork. The presence of the .o and .so files in Netflix's commit breaks install_github 
install_github(repo = "mmolaro/Surus", subdir = "src/RAD")

**Comment by asstergiBSQ** [comment]
Thanks @mmolaro 
I installed it from your fork and worked great!! :D

**Comment by ccolburn** [comment]
Thanks @mmolaro ... Appreciate you fixing that for us!
